### PR TITLE
Fixed WP 4.3 PHP warning in WYSIWYG value

### PR DESCRIPTION
**Pull request by fburatti**
Also fix for switchEditors (ACF Pro)

### CODE REVIEW

**Comment by puntonero** [comment]
It works!

**Comment by mohdqasim98** [comment]
Works Great

**Comment by beta2k** [comment]
Seems to work for me now too. Fingers crossed.

**Comment by mohdqasim98** [comment]
Solved now
Thanks

**Comment by denniskoster** [comment]
Worked for me! Thanks!

**Comment by haywirer** [comment]
I worked it around adding this at funcions.php

function override_mce_options($initArray){
    $initArray["selector"] = "#content, textarea[id*=wysiwyg-acf]";
    return $initArray;
 }
 add_filter('tiny_mce_before_init', 'override_mce_options');

**Pull request merged**
